name = "roll-dorado-casino-co-at"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-casino.co.at"
HMAC_KEY = "fa8c0b7e8383889e6b4e501e5433904b89f393b765e2dc263f16ee985f6e145f"
COOKIE_NAME = "wno"
PLAY_PATH = "play-now"
BUTTON_ID = "p1fb6e5244d5a9133a3a97a59f8a975d4"
GATE_SALT = "fe88da781d3b0b01"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "ub3r"
CTA_SELECTOR = ".play-button"
